import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import AuthContext from "@/context/AuthContext";
import SWRConfigContext from "@/context/SWRConfigContext";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Instogram",
    description: "Generated by myungwan for Next.js Side Project",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${openSans.className} w-full max-w-screen-xl mx-auto overflow-auto`}
            >
                <AuthContext>
                    <header className="sticky top-0 bg-white z-10 border-b">
                        <Navbar />
                    </header>
                    <main className="w-full flex justify-center bg-neutral-50 min-h-full">
                        <SWRConfigContext>{children}</SWRConfigContext>
                    </main>
                </AuthContext>
                <div id="modalPortal"></div>
            </body>
        </html>
    );
}
